require 'joule/array'
require 'joule/data_point'
require 'joule/marker'
require 'joule/marker_calculator'
require 'joule/peak_power_calculator'
require 'joule/power_calculator'
require 'joule/tcx_parser'
require 'joule/tcx_properties'